"""
参考实现生成器 —— 生成 torch 基准的 ref.py 和统一 benchmark 框架。

功能:
  1. 根据 OperatorSpec 生成 ref.py (PyTorch 参考实现)
  2. 生成 benchmark_runner.py (统一 benchmark)
  3. 确保 CUDA 代码包含 extern "C" 入口
"""
from __future__ import annotations
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

DTYPE_MAP = {
    "fp16": ("float16", "half"),
    "fp32": ("float32", "float"),
    "bf16": ("bfloat16", "__nv_bfloat16"),
    "fp64": ("float64", "double"),
    "int8": ("int8", "int8_t"),
    "int32": ("int32", "int"),
}


def _torch_dtype(dtype: str) -> str:
    return DTYPE_MAP.get(dtype, ("float16", "half"))[0]

def _c_dtype(dtype: str) -> str:
    return DTYPE_MAP.get(dtype, ("float16", "half"))[1]


# ══════════════════════════════════════
# ref.py 模板
# ══════════════════════════════════════

_HEADER = '''"""
{operator} — PyTorch reference implementation and CUDA runner.
Auto-generated by cuda_opt_agent.

Usage:
    python ref.py                                      # Self-test
    python ref.py --benchmark                         # Torch baseline benchmark
    python ref.py --cuda code.cu --check              # Compile + correctness
    python ref.py --cuda code.cu --benchmark          # Compile + benchmark
"""
import argparse
import ctypes
import inspect
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any
import torch
import numpy as np

OPERATOR_NAME = "{operator}"
DEFAULT_DTYPE = torch.{torch_dtype}
DEVICE = "cuda"
'''

_GEMM_BODY = '''
DEFAULT_M = {M}
DEFAULT_N = {N}
DEFAULT_K = {K}

def generate_inputs(M: int = DEFAULT_M, N: int = DEFAULT_N, K: int = DEFAULT_K,
                    dtype: torch.dtype = DEFAULT_DTYPE, device: str = DEVICE
                    ) -> dict[str, Any]:
    A = torch.randn(M, K, dtype=dtype, device=device)
    B = torch.randn(K, N, dtype=dtype, device=device)
    return {{"A": A, "B": B, "M": M, "N": N, "K": K}}

def reference_impl(inputs: dict[str, Any]) -> torch.Tensor:
    return torch.mm(inputs["A"], inputs["B"])

def get_output_shape(inputs: dict[str, Any]) -> tuple[int, ...]:
    return (inputs["M"], inputs["N"])

def get_extern_c_signature() -> str:
    return 'extern "C" void {operator}_kernel(const {c_dtype}* A, const {c_dtype}* B, {c_dtype}* C, int M, int N, int K)'

def get_kernel_launch_args(inputs: dict[str, Any]) -> tuple[list, torch.Tensor]:
    M, K = inputs["A"].shape
    _, N = inputs["B"].shape
    C = torch.empty(M, N, dtype=inputs["A"].dtype, device=inputs["A"].device)
    return [ctypes.c_void_p(inputs["A"].data_ptr()), ctypes.c_void_p(inputs["B"].data_ptr()),
            ctypes.c_void_p(C.data_ptr()), ctypes.c_int(M), ctypes.c_int(N), ctypes.c_int(K)], C
'''

_SOFTMAX_BODY = '''
DEFAULT_B = {B}
DEFAULT_N = {N}

def generate_inputs(B: int = DEFAULT_B, N: int = DEFAULT_N,
                    dtype: torch.dtype = DEFAULT_DTYPE, device: str = DEVICE
                    ) -> dict[str, Any]:
    X = torch.randn(B, N, dtype=dtype, device=device)
    return {{"X": X, "B": B, "N": N}}

def reference_impl(inputs: dict[str, Any]) -> torch.Tensor:
    return torch.softmax(inputs["X"], dim=-1)

def get_output_shape(inputs: dict[str, Any]) -> tuple[int, ...]:
    return (inputs["B"], inputs["N"])

def get_extern_c_signature() -> str:
    return 'extern "C" void {operator}_kernel(const {c_dtype}* input, {c_dtype}* output, int B, int N)'

def get_kernel_launch_args(inputs: dict[str, Any]) -> tuple[list, torch.Tensor]:
    B, N = inputs["X"].shape
    output = torch.empty_like(inputs["X"])
    return [ctypes.c_void_p(inputs["X"].data_ptr()), ctypes.c_void_p(output.data_ptr()),
            ctypes.c_int(B), ctypes.c_int(N)], output
'''

_LAYERNORM_BODY = '''
DEFAULT_B = {B}
DEFAULT_N = {N}
EPSILON = 1e-5

def generate_inputs(B: int = DEFAULT_B, N: int = DEFAULT_N,
                    epsilon: float = EPSILON,
                    dtype: torch.dtype = DEFAULT_DTYPE, device: str = DEVICE
                    ) -> dict[str, Any]:
    torch.manual_seed(12345)
    X = torch.empty(B, N, dtype=dtype, device=device).uniform_(-2.0, 2.0)
    gamma = torch.empty(N, dtype=dtype, device=device).uniform_(0.5, 1.5)
    beta = torch.empty(N, dtype=dtype, device=device).uniform_(-0.5, 0.5)
    return {{"X": X, "gamma": gamma, "beta": beta, "B": B, "N": N, "epsilon": epsilon}}

def reference_impl(inputs: dict[str, Any]) -> torch.Tensor:
    return torch.nn.functional.layer_norm(
        inputs["X"], [inputs["N"]], inputs["gamma"], inputs["beta"],
        eps=float(inputs.get("epsilon", EPSILON)))

def get_output_shape(inputs: dict[str, Any]) -> tuple[int, ...]:
    return (inputs["B"], inputs["N"])

def get_extern_c_signature() -> str:
    return ('extern "C" void {operator}_kernel(const {c_dtype}* input, const {c_dtype}* gamma, '
            'const {c_dtype}* beta, {c_dtype}* output, int B, int N, float epsilon)')

def get_kernel_launch_args(inputs: dict[str, Any]) -> tuple[list, torch.Tensor]:
    B, N = inputs["X"].shape
    output = torch.empty_like(inputs["X"])
    return [ctypes.c_void_p(inputs["X"].data_ptr()), ctypes.c_void_p(inputs["gamma"].data_ptr()),
            ctypes.c_void_p(inputs["beta"].data_ptr()), ctypes.c_void_p(output.data_ptr()),
            ctypes.c_int(B), ctypes.c_int(N), ctypes.c_float(float(inputs.get("epsilon", EPSILON)))], output
'''

_GENERIC_BODY = '''
DEFAULT_SHAPE = {default_shape}

def generate_inputs(shape: list[int] | None = None,
                    dtype: torch.dtype = DEFAULT_DTYPE, device: str = DEVICE
                    ) -> dict[str, Any]:
    if shape is None:
        shape = DEFAULT_SHAPE
    X = torch.randn(*shape, dtype=dtype, device=device)
    return {{"X": X, "shape": shape}}

def reference_impl(inputs: dict[str, Any]) -> torch.Tensor:
    # TODO: Replace with actual {operator} reference
    return inputs["X"]

def get_output_shape(inputs: dict[str, Any]) -> tuple[int, ...]:
    return tuple(inputs["shape"])

def get_extern_c_signature() -> str:
    return 'extern "C" void {operator}_kernel(const {c_dtype}* input, {c_dtype}* output, int N)'

def get_kernel_launch_args(inputs: dict[str, Any]) -> tuple[list, torch.Tensor]:
    X = inputs["X"]
    output = torch.empty_like(X)
    return [ctypes.c_void_p(X.data_ptr()), ctypes.c_void_p(output.data_ptr()), ctypes.c_int(X.numel())], output
'''

_FOOTER = '''

def _resolve_torch_dtype(name: str | None) -> torch.dtype:
    if name is None:
        return DEFAULT_DTYPE
    normalized = name.lower().replace("torch.", "")
    aliases = {
        "fp16": torch.float16,
        "float16": torch.float16,
        "half": torch.float16,
        "bf16": torch.bfloat16,
        "bfloat16": torch.bfloat16,
        "fp32": torch.float32,
        "float32": torch.float32,
        "float": torch.float32,
        "fp64": torch.float64,
        "float64": torch.float64,
        "double": torch.float64,
    }
    if normalized in aliases:
        return aliases[normalized]
    if hasattr(torch, normalized):
        value = getattr(torch, normalized)
        if isinstance(value, torch.dtype):
            return value
    raise ValueError(f"Unsupported dtype: {name}")


def _parse_scalar_or_list(value: str) -> Any:
    value = value.strip().strip("[]")
    if "," in value:
        return [int(part.strip()) for part in value.split(",") if part.strip()]
    try:
        return int(value)
    except ValueError:
        return float(value)


def _parse_shape_kwargs(items: list[str], unknown: list[str] | None = None) -> dict[str, Any]:
    result: dict[str, Any] = {}
    tokens = list(items or [])
    tokens.extend(token for token in (unknown or []) if "=" in token and not token.startswith("--"))
    for token in tokens:
        if "=" not in token:
            continue
        key, value = token.split("=", 1)
        result[key.strip()] = _parse_scalar_or_list(value)
    return result


def _generate_inputs_from_cli(shape_kwargs: dict[str, Any], *, dtype: torch.dtype,
                              device: str, epsilon: float) -> dict[str, Any]:
    params = inspect.signature(generate_inputs).parameters
    kw = {k: v for k, v in shape_kwargs.items() if k in params}
    if "epsilon" in params:
        kw["epsilon"] = epsilon
    if "dtype" in params:
        kw["dtype"] = dtype
    if "device" in params:
        kw["device"] = device
    return generate_inputs(**kw)


def _move_inputs_to_device(inputs: dict[str, Any], device: str) -> dict[str, Any]:
    if not str(device).startswith("cuda"):
        return inputs
    moved: dict[str, Any] = {}
    for key, value in inputs.items():
        moved[key] = value.to(device, non_blocking=True) if isinstance(value, torch.Tensor) else value
    torch.cuda.synchronize()
    return moved


def _generate_cuda_inputs(shape_kwargs: dict[str, Any], *, dtype: torch.dtype,
                          device: str, epsilon: float) -> dict[str, Any]:
    # Initialize on CPU so ncu does not profile PyTorch random-fill kernels before
    # the target CUDA kernel launches.
    init_device = "cpu" if str(device).startswith("cuda") else device
    inputs = _generate_inputs_from_cli(shape_kwargs, dtype=dtype, device=init_device, epsilon=epsilon)
    return _move_inputs_to_device(inputs, device)


def validate_correctness(cuda_output: torch.Tensor, ref_output: torch.Tensor, *,
                         atol: float = 1e-2, rtol: float = 1e-2,
                         sample_ratio: float = 1.0) -> dict[str, Any]:
    if sample_ratio < 1.0:
        numel = cuda_output.numel()
        n = max(1, int(numel * sample_ratio))
        idx = torch.randperm(numel, device=cuda_output.device)[:n]
        cf, rf = cuda_output.flatten()[idx], ref_output.flatten()[idx]
    else:
        cf, rf = cuda_output.flatten(), ref_output.flatten()
    cf = cf.float()
    rf = rf.float()
    max_abs = (cf - rf).abs().max().item()
    max_rel = ((cf - rf).abs() / (rf.abs() + 1e-8)).max().item()
    passed = torch.allclose(cf, rf, atol=atol, rtol=rtol)
    return {"passed": bool(passed), "max_abs_error": max_abs, "max_rel_error": max_rel,
            "atol": atol, "rtol": rtol, "num_elements_checked": cf.numel()}


def _auto_link_flags(cu_file: Path) -> list[str]:
    try:
        text = cu_file.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return []
    flags: list[str] = []
    if "cublasLt.h" in text:
        flags.extend(["-lcublasLt", "-lcublas"])
    elif "cublas_v2.h" in text:
        flags.append("-lcublas")
    if "cudnn.h" in text:
        flags.append("-lcudnn")
    return list(dict.fromkeys(flags))


def compile_cuda_shared(cu_file: str | Path, *, arch: str = "sm_80",
                        output: str | Path | None = None,
                        extra_flags: list[str] | None = None,
                        timeout: int = 120) -> Path:
    cu_path = Path(cu_file).expanduser().resolve()
    if not cu_path.exists():
        raise RuntimeError(f"CUDA source not found: {cu_path}")
    if cu_path.suffix == ".so":
        return cu_path
    nvcc = shutil.which("nvcc")
    if not nvcc:
        raise RuntimeError("nvcc not found; ensure CUDA Toolkit is installed")
    so_path = Path(output).expanduser().resolve() if output else cu_path.with_suffix(".so")
    if so_path.exists() and so_path.stat().st_mtime >= cu_path.stat().st_mtime:
        return so_path
    arch_num = arch.replace("sm_", "")
    cmd = [
        nvcc,
        "-shared",
        "-Xcompiler", "-fPIC",
        "-O3",
        "-lineinfo",
        "-allow-unsupported-compiler",
        "-D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH",
        f"-gencode=arch=compute_{arch_num},code=sm_{arch_num}",
        f"-I{cu_path.parent}",
        "-o", str(so_path),
        str(cu_path),
    ]
    cmd.extend(extra_flags or [])
    cmd.extend(_auto_link_flags(cu_path))
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        errors="replace",
        timeout=timeout,
        cwd=str(cu_path.parent),
    )
    if result.returncode != 0:
        raise RuntimeError(f"compile failed: {result.stderr[:4000]}")
    return so_path


def load_cuda_kernel(cu_file: str | Path, *, func_name: str, arch: str,
                     so_path: str | Path | None = None,
                     extra_flags: list[str] | None = None,
                     timeout: int = 120):
    shared = compile_cuda_shared(cu_file, arch=arch, output=so_path,
                                 extra_flags=extra_flags, timeout=timeout)
    lib = ctypes.CDLL(str(shared))
    try:
        return getattr(lib, func_name), shared
    except AttributeError as exc:
        raise RuntimeError(f"function '{func_name}' not found in {shared}") from exc


def run_cuda_correctness(func, *, shape_kwargs: dict[str, Any], dtype: torch.dtype,
                         device: str, epsilon: float, atol: float, rtol: float) -> dict[str, Any]:
    inputs = _generate_cuda_inputs(shape_kwargs, dtype=dtype, device=device, epsilon=epsilon)
    ref_out = reference_impl(inputs)
    launch_args, cuda_out = get_kernel_launch_args(inputs)
    func(*launch_args)
    torch.cuda.synchronize()
    result = validate_correctness(cuda_out, ref_out, atol=atol, rtol=rtol)
    result.update({
        "op": OPERATOR_NAME,
        "correct": result["passed"],
        "compile_ok": True,
        "max_abs_err": result["max_abs_error"],
        "max_rel_err": result["max_rel_error"],
        "message": "ok" if result["passed"] else "mismatch",
    })
    return result


def benchmark_cuda_kernel(func, *, n_warmup: int = 10, n_measure: int = 100,
                          shape_kwargs: dict[str, Any] | None = None,
                          dtype: torch.dtype = DEFAULT_DTYPE,
                          device: str = DEVICE,
                          epsilon: float = 1e-5) -> dict[str, Any]:
    inputs = _generate_cuda_inputs(shape_kwargs or {}, dtype=dtype, device=device, epsilon=epsilon)
    launch_args, _ = get_kernel_launch_args(inputs)
    for _ in range(n_warmup):
        func(*launch_args)
    torch.cuda.synchronize()
    starts = [torch.cuda.Event(enable_timing=True) for _ in range(n_measure)]
    ends = [torch.cuda.Event(enable_timing=True) for _ in range(n_measure)]
    for i in range(n_measure):
        starts[i].record()
        func(*launch_args)
        ends[i].record()
    torch.cuda.synchronize()
    times = sorted(float(s.elapsed_time(e)) for s, e in zip(starts, ends))
    p95_idx = min(len(times) - 1, int(len(times) * 0.95))
    avg = sum(times) / len(times)
    return {
        "op": OPERATOR_NAME,
        "latencies_ms": times,
        "latency_ms_median": times[len(times) // 2],
        "latency_ms_p95": times[p95_idx],
        "avg_ms": avg,
        "total_ms": sum(times),
        "warmup": n_warmup,
        "rounds": n_measure,
        "compile_ok": True,
    }


def benchmark_torch_reference(n_warmup: int = 10, n_measure: int = 100, **kw) -> dict[str, float]:
    inputs = generate_inputs(**kw)
    for _ in range(n_warmup):
        _ = reference_impl(inputs)
    torch.cuda.synchronize()
    starts = [torch.cuda.Event(enable_timing=True) for _ in range(n_measure)]
    ends = [torch.cuda.Event(enable_timing=True) for _ in range(n_measure)]
    for i in range(n_measure):
        starts[i].record(); _ = reference_impl(inputs); ends[i].record()
    torch.cuda.synchronize()
    times = sorted(s.elapsed_time(e) for s, e in zip(starts, ends))
    trim = max(1, len(times) // 10)
    t = times[trim:-trim] if len(times) > 2 * trim else times
    return {"mean_ms": sum(t)/len(t), "median_ms": t[len(t)//2],
            "min_ms": min(times), "max_ms": max(times)}


def _print_json(payload: dict[str, Any]) -> None:
    print(json.dumps(payload, sort_keys=True))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--benchmark", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--cuda", default="", help="CUDA .cu file or prebuilt .so to test")
    parser.add_argument("--func", default=f"{OPERATOR_NAME}_kernel")
    parser.add_argument("--arch", default="sm_80")
    parser.add_argument("--so", default=None, help="Optional output path for compiled shared library")
    parser.add_argument("--warmup", type=int, default=10)
    parser.add_argument("--rounds", "--iters", "--measure", dest="rounds", type=int, default=100)
    parser.add_argument("--shape", nargs="*", default=[])
    parser.add_argument("--epsilon", type=float, default=float(globals().get("EPSILON", 1e-5)))
    parser.add_argument("--atol", type=float, default=1e-2)
    parser.add_argument("--rtol", type=float, default=1e-2)
    parser.add_argument("--dtype", default=None)
    parser.add_argument("--device", default=DEVICE)
    parser.add_argument("--compile-timeout", type=int, default=120)
    parser.add_argument("--extra-nvcc-flag", action="append", default=[])
    args, unknown = parser.parse_known_args()

    shape_kwargs = _parse_shape_kwargs(args.shape, unknown)
    dtype = _resolve_torch_dtype(args.dtype)

    if args.cuda:
        compile_ok = False
        try:
            func, shared = load_cuda_kernel(
                args.cuda,
                func_name=args.func,
                arch=args.arch,
                so_path=args.so,
                extra_flags=args.extra_nvcc_flag,
                timeout=args.compile_timeout,
            )
            compile_ok = True
            if args.check:
                payload = run_cuda_correctness(
                    func,
                    shape_kwargs=shape_kwargs,
                    dtype=dtype,
                    device=args.device,
                    epsilon=args.epsilon,
                    atol=args.atol,
                    rtol=args.rtol,
                )
                payload["shared_library"] = str(shared)
                _print_json(payload)
                return 0 if payload["passed"] else 1
            payload = benchmark_cuda_kernel(
                func,
                n_warmup=args.warmup,
                n_measure=args.rounds,
                shape_kwargs=shape_kwargs,
                dtype=dtype,
                device=args.device,
                epsilon=args.epsilon,
            )
            payload["shared_library"] = str(shared)
            _print_json(payload)
            return 0
        except Exception as exc:
            _print_json({
                "op": OPERATOR_NAME,
                "correct": False,
                "passed": False,
                "compile_ok": compile_ok,
                "message": str(exc),
                "error": str(exc),
            })
            return 1

    inputs = _generate_inputs_from_cli(shape_kwargs, dtype=dtype, device=args.device, epsilon=args.epsilon)
    output = reference_impl(inputs)
    if args.benchmark:
        bench_kwargs = {k: v for k, v in shape_kwargs.items() if k in inspect.signature(generate_inputs).parameters}
        if "epsilon" in inspect.signature(generate_inputs).parameters:
            bench_kwargs["epsilon"] = args.epsilon
        bench_kwargs["dtype"] = dtype
        bench_kwargs["device"] = args.device
        payload = benchmark_torch_reference(args.warmup, args.rounds, **bench_kwargs)
        payload.update({"op": OPERATOR_NAME, "backend": "torch"})
        _print_json(payload)
        return 0

    print(f"\\n=== {OPERATOR_NAME} Reference ===")
    print(f"Output shape: {output.shape}, dtype: {output.dtype}")
    print(f"Extern C: {get_extern_c_signature()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


# ══════════════════════════════════════
# benchmark_runner.py 模板
# ══════════════════════════════════════

_RUNNER = '''"""
Unified CUDA Kernel Benchmark Runner.

Usage:
    python benchmark_runner.py code.cu                   # compile + correctness + bench
    python benchmark_runner.py code.cu --compare-torch   # compare with torch
    python benchmark_runner.py code.cu --correctness-only
"""
import argparse, ctypes, subprocess, sys, time
from pathlib import Path
import torch, numpy as np

sys.path.insert(0, str(Path(__file__).parent))
import ref

def compile_cuda(cu, out=None, arch="sm_80", extra=None):
    cu = str(Path(cu).resolve())
    out = out or cu.replace(".cu", ".so")
    cmd = ["nvcc", "-shared", "-Xcompiler", "-fPIC", f"-arch={{arch}}", "-O3", "-o", out, cu]
    if extra: cmd.extend(extra)
    print(f"Compiling: {{' '.join(cmd)}}")
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print(f"Compile failed:\\n{{r.stderr}}"); sys.exit(1)
    return out

def benchmark(func, args, warmup=10, measure=100):
    for _ in range(warmup): func(*args)
    torch.cuda.synchronize()
    ss = [torch.cuda.Event(enable_timing=True) for _ in range(measure)]
    es = [torch.cuda.Event(enable_timing=True) for _ in range(measure)]
    for i in range(measure):
        ss[i].record(); func(*args); es[i].record()
    torch.cuda.synchronize()
    t = sorted(s.elapsed_time(e) for s, e in zip(ss, es))
    trim = max(1, len(t)//10)
    tt = t[trim:-trim] if len(t) > 2*trim else t
    return {{"mean_ms": sum(tt)/len(tt), "median_ms": tt[len(tt)//2], "min_ms": min(t), "max_ms": max(t)}}

def main():
    p = argparse.ArgumentParser()
    p.add_argument("cu_file")
    p.add_argument("--func", default=None)
    p.add_argument("--arch", default="sm_80")
    p.add_argument("--warmup", type=int, default=10)
    p.add_argument("--measure", type=int, default=100)
    p.add_argument("--compare-torch", action="store_true")
    p.add_argument("--correctness-only", action="store_true")
    p.add_argument("--extra-flags", nargs="*", default=[])
    a = p.parse_args()
    fn = a.func or f"{{ref.OPERATOR_NAME}}_kernel"
    so = compile_cuda(a.cu_file, arch=a.arch, extra=a.extra_flags)
    lib = ctypes.CDLL(so); kf = getattr(lib, fn)

    print("\\n=== Correctness ===")
    inputs = ref.generate_inputs()
    ref_out = ref.reference_impl(inputs)
    la, cuda_out = ref.get_kernel_launch_args(inputs)
    kf(*la); torch.cuda.synchronize()
    c = ref.validate_correctness(cuda_out, ref_out)
    print(f"  Status: {{'PASSED' if c['passed'] else 'FAILED'}}")
    print(f"  Max abs error: {{c['max_abs_error']:.6e}}")
    if a.correctness_only: sys.exit(0 if c["passed"] else 1)

    print("\\n=== CUDA Kernel Benchmark ===")
    la2, _ = ref.get_kernel_launch_args(ref.generate_inputs())
    r = benchmark(kf, la2, a.warmup, a.measure)
    for k, v in r.items(): print(f"  {{k}}: {{v:.4f}}")

    if a.compare_torch:
        print("\\n=== Torch Reference ===")
        tr = ref.benchmark_torch_reference(n_warmup=a.warmup, n_measure=a.measure)
        for k, v in tr.items(): print(f"  {{k}}: {{v:.4f}}")
        print(f"\\n  Speedup vs Torch: {{tr['mean_ms']/r['mean_ms']:.2f}}x")

if __name__ == "__main__": main()
'''


_LAYERNORM_EXECUTABLE_HARNESS = r'''

// ---- cuda_opt_agent executable harness for layernorm ----
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <string>
#include <vector>

static int _coa_arg_int(int argc, char** argv, const char* name, int default_value) {
    for (int i = 1; i + 1 < argc; ++i) {
        if (std::strcmp(argv[i], name) == 0) return std::atoi(argv[i + 1]);
    }
    return default_value;
}

static float _coa_arg_float(int argc, char** argv, const char* name, float default_value) {
    for (int i = 1; i + 1 < argc; ++i) {
        if (std::strcmp(argv[i], name) == 0) return std::atof(argv[i + 1]);
    }
    return default_value;
}

static bool _coa_has_flag(int argc, char** argv, const char* name) {
    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], name) == 0) return true;
    }
    return false;
}

static void _coa_parse_shape(int argc, char** argv, int& B, int& N) {
    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--shape") != 0) continue;
        for (int j = i + 1; j < argc && std::strncmp(argv[j], "--", 2) != 0; ++j) {
            std::string item(argv[j]);
            auto pos = item.find('=');
            if (pos == std::string::npos) continue;
            std::string key = item.substr(0, pos);
            int value = std::atoi(item.substr(pos + 1).c_str());
            if (key == "B" || key == "M" || key == "rows") B = value;
            if (key == "N" || key == "K" || key == "cols") N = value;
        }
    }
}

static void _coa_check_cuda(cudaError_t err, const char* what) {
    if (err == cudaSuccess) return;
    std::fprintf(stderr, "%s failed: %s\n", what, cudaGetErrorString(err));
    std::exit(2);
}

static void _coa_fill_inputs(std::vector<half>& input, std::vector<half>& gamma, std::vector<half>& beta, int B, int N) {
    for (size_t i = 0; i < input.size(); ++i) {
        float v = static_cast<float>((static_cast<int>(i % 257) - 128)) / 37.0f;
        input[i] = __float2half(v);
    }
    for (int j = 0; j < N; ++j) {
        gamma[j] = __float2half(1.0f + 0.01f * static_cast<float>(j % 7));
        beta[j] = __float2half(0.01f * static_cast<float>((j % 5) - 2));
    }
}

static void _coa_layernorm_ref(
    const std::vector<half>& input,
    const std::vector<half>& gamma,
    const std::vector<half>& beta,
    std::vector<float>& ref,
    int B,
    int N,
    float epsilon) {
    for (int row = 0; row < B; ++row) {
        int base = row * N;
        double sum = 0.0;
        double sqsum = 0.0;
        for (int col = 0; col < N; ++col) {
            float x = __half2float(input[base + col]);
            sum += x;
            sqsum += static_cast<double>(x) * static_cast<double>(x);
        }
        float mean = static_cast<float>(sum / static_cast<double>(N));
        float variance = static_cast<float>(sqsum / static_cast<double>(N) - static_cast<double>(mean) * mean);
        variance = std::max(variance, 0.0f);
        float inv_std = 1.0f / std::sqrt(variance + epsilon);
        for (int col = 0; col < N; ++col) {
            float x = __half2float(input[base + col]);
            float g = __half2float(gamma[col]);
            float b = __half2float(beta[col]);
            ref[base + col] = (x - mean) * inv_std * g + b;
        }
    }
}

int main(int argc, char** argv) {
    int B = 1024;
    int N = 1024;
    _coa_parse_shape(argc, argv, B, N);
    int warmup = _coa_arg_int(argc, argv, "--warmup", 10);
    int rounds = _coa_arg_int(argc, argv, "--rounds", _coa_arg_int(argc, argv, "--iters", 100));
    float atol = _coa_arg_float(argc, argv, "--atol", 1e-2f);
    float rtol = _coa_arg_float(argc, argv, "--rtol", 5e-2f);
    const float epsilon = 1e-5f;
    bool check = _coa_has_flag(argc, argv, "--check");

    if (B <= 0 || N <= 0 || warmup < 0 || rounds <= 0) {
        std::fprintf(stderr, "invalid arguments: B=%d N=%d warmup=%d rounds=%d\n", B, N, warmup, rounds);
        return 2;
    }

    size_t numel = static_cast<size_t>(B) * static_cast<size_t>(N);
    std::vector<half> h_input(numel), h_gamma(N), h_beta(N), h_output(numel);
    _coa_fill_inputs(h_input, h_gamma, h_beta, B, N);

    half* d_input = nullptr;
    half* d_gamma = nullptr;
    half* d_beta = nullptr;
    half* d_output = nullptr;
    _coa_check_cuda(cudaMalloc(&d_input, numel * sizeof(half)), "cudaMalloc input");
    _coa_check_cuda(cudaMalloc(&d_gamma, static_cast<size_t>(N) * sizeof(half)), "cudaMalloc gamma");
    _coa_check_cuda(cudaMalloc(&d_beta, static_cast<size_t>(N) * sizeof(half)), "cudaMalloc beta");
    _coa_check_cuda(cudaMalloc(&d_output, numel * sizeof(half)), "cudaMalloc output");
    _coa_check_cuda(cudaMemcpy(d_input, h_input.data(), numel * sizeof(half), cudaMemcpyHostToDevice), "cudaMemcpy input");
    _coa_check_cuda(cudaMemcpy(d_gamma, h_gamma.data(), static_cast<size_t>(N) * sizeof(half), cudaMemcpyHostToDevice), "cudaMemcpy gamma");
    _coa_check_cuda(cudaMemcpy(d_beta, h_beta.data(), static_cast<size_t>(N) * sizeof(half), cudaMemcpyHostToDevice), "cudaMemcpy beta");

    if (check) {
        layernorm_kernel(d_input, d_gamma, d_beta, d_output, B, N, epsilon);
        _coa_check_cuda(cudaGetLastError(), "layernorm_kernel");
        _coa_check_cuda(cudaMemcpy(h_output.data(), d_output, numel * sizeof(half), cudaMemcpyDeviceToHost), "cudaMemcpy output");

        std::vector<float> ref(numel);
        _coa_layernorm_ref(h_input, h_gamma, h_beta, ref, B, N, epsilon);
        float max_abs = 0.0f;
        float max_rel = 0.0f;
        bool correct = true;
        for (size_t i = 0; i < numel; ++i) {
            float got = __half2float(h_output[i]);
            float want = ref[i];
            float abs_err = std::fabs(got - want);
            float rel_err = abs_err / (std::fabs(want) + 1e-6f);
            max_abs = std::max(max_abs, abs_err);
            max_rel = std::max(max_rel, rel_err);
            if (abs_err > atol + rtol * std::fabs(want)) correct = false;
        }
        std::printf("{\"correct\":%s,\"max_abs_error\":%.8g,\"max_rel_error\":%.8g,\"message\":\"%s\"}\n",
                    correct ? "true" : "false", max_abs, max_rel, correct ? "ok" : "mismatch");
        cudaFree(d_input); cudaFree(d_gamma); cudaFree(d_beta); cudaFree(d_output);
        return correct ? 0 : 1;
    }

    for (int i = 0; i < warmup; ++i) {
        layernorm_kernel(d_input, d_gamma, d_beta, d_output, B, N, epsilon);
    }
    _coa_check_cuda(cudaDeviceSynchronize(), "warmup sync");

    std::vector<float> latencies;
    latencies.reserve(rounds);
    cudaEvent_t start, stop;
    _coa_check_cuda(cudaEventCreate(&start), "cudaEventCreate start");
    _coa_check_cuda(cudaEventCreate(&stop), "cudaEventCreate stop");
    for (int i = 0; i < rounds; ++i) {
        _coa_check_cuda(cudaEventRecord(start), "cudaEventRecord start");
        layernorm_kernel(d_input, d_gamma, d_beta, d_output, B, N, epsilon);
        _coa_check_cuda(cudaEventRecord(stop), "cudaEventRecord stop");
        _coa_check_cuda(cudaEventSynchronize(stop), "cudaEventSynchronize stop");
        float ms = 0.0f;
        _coa_check_cuda(cudaEventElapsedTime(&ms, start, stop), "cudaEventElapsedTime");
        latencies.push_back(ms);
    }
    std::sort(latencies.begin(), latencies.end());
    float median = latencies[latencies.size() / 2];
    size_t p95_idx = std::min(latencies.size() - 1, static_cast<size_t>(latencies.size() * 0.95));
    float p95 = latencies[p95_idx];

    std::printf("{\"latency_ms_median\":%.8g,\"latency_ms_p95\":%.8g,\"latencies_ms\":[", median, p95);
    for (size_t i = 0; i < latencies.size(); ++i) {
        if (i) std::printf(",");
        std::printf("%.8g", latencies[i]);
    }
    std::printf("]}\n");

    cudaEventDestroy(start); cudaEventDestroy(stop);
    cudaFree(d_input); cudaFree(d_gamma); cudaFree(d_beta); cudaFree(d_output);
    return 0;
}
'''


def ensure_executable_harness(kernel_code: str, operator: str) -> str:
    """Keep candidate CUDA focused on the kernel; ref.py owns test harnesses."""
    return kernel_code


# ══════════════════════════════════════
# 生成函数
# ══════════════════════════════════════

def generate_ref_py(
    operator: str, *,
    shapes: dict[str, list[int]] | None = None,
    shape_profiles: list[dict] | None = None,
    dtypes: dict[str, str] | None = None,
    default_dtype: str = "fp16",
    output_dir: str | Path = ".",
) -> Path:
    """生成 ref.py。"""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    td = _torch_dtype(default_dtype)
    cd = _c_dtype(default_dtype)
    content = _HEADER.format(operator=operator, torch_dtype=td)

    op = operator.lower()
    if op == "gemm":
        M, N, K = 4096, 4096, 4096
        if shapes:
            A = shapes.get("A", [4096, 4096]); B = shapes.get("B", [4096, 4096])
            M, K, N = A[0], A[1], B[1]
        elif shape_profiles:
            p = shape_profiles[0]; M, N, K = p.get("M", 4096), p.get("N", 4096), p.get("K", 4096)
        content += _GEMM_BODY.format(M=M, N=N, K=K, operator=operator, c_dtype=cd)
    elif op == "softmax":
        B, N = 4096, 4096
        if shape_profiles:
            p = shape_profiles[0]; B, N = p.get("B", 4096), p.get("N", 4096)
        content += _SOFTMAX_BODY.format(B=B, N=N, operator=operator, c_dtype=cd)
    elif op == "layernorm":
        B, N = 4096, 4096
        if shape_profiles:
            p = shape_profiles[0]; B, N = p.get("B", 4096), p.get("N", 4096)
        content += _LAYERNORM_BODY.format(B=B, N=N, operator=operator, c_dtype=cd)
    else:
        ds = [4096]
        if shapes:
            ds = list(shapes.values())[0] if shapes else [4096]
        elif shape_profiles:
            ds = list(shape_profiles[0].values())
        content += _GENERIC_BODY.format(default_shape=ds, operator=operator, c_dtype=cd)

    content += _FOOTER
    path = output_dir / "ref.py"
    path.write_text(content, encoding="utf-8")
    logger.info("Generated ref.py at %s", path)
    return path


def generate_benchmark_runner(operator: str, *, output_dir: str | Path = ".") -> Path:
    """生成 benchmark_runner.py。"""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    content = _RUNNER.format(operator=operator)
    path = output_dir / "benchmark_runner.py"
    path.write_text(content, encoding="utf-8")
    logger.info("Generated benchmark_runner.py at %s", path)
    return path


def wrap_with_extern_c(kernel_code: str, operator: str, *,
                        extern_c_params: str = "", version: str = "v0") -> str:
    """确保 CUDA 代码包含 extern "C" 入口。"""
    if 'extern "C"' in kernel_code:
        return kernel_code
    template = '''// {operator} kernel — {version}
// extern "C" wrapper for unified benchmarking

{code}

extern "C" void {operator}_kernel({params}) {{
    // TODO: Configure grid/block and launch kernel
    // Example:
    // dim3 block(256);
    // dim3 grid((N + 255) / 256);
    // kernel_impl<<<grid, block>>>(...);
    // cudaDeviceSynchronize();
}}
'''
    return template.format(operator=operator, version=version,
                            code=kernel_code, params=extern_c_params)


def build_extern_c_params(operator: str, dtypes: dict | None = None) -> str:
    """构建 extern C 参数签名。"""
    dtype = "fp16"
    if dtypes:
        dtype = list(dtypes.values())[0]
    ct = _c_dtype(dtype)
    op = operator.lower()
    if op == "gemm":
        return f"const {ct}* A, const {ct}* B, {ct}* C, int M, int N, int K"
    elif op == "softmax":
        return f"const {ct}* input, {ct}* output, int B, int N"
    elif op == "layernorm":
        return f"const {ct}* input, const {ct}* gamma, const {ct}* beta, {ct}* output, int B, int N, float epsilon"
    else:
        return f"const {ct}* input, {ct}* output, int N"
